apiVersion: v1
kind: ConfigMap
metadata:
  name: file-ingester-config
data:
  INPUT_DIR:      "/data/normalized"
  PROCESSED_DIR:  "/data/processed"
  FAILED_DIR:     "/data/failed"
  OUTPUT_DIR:     "/data/output"
  CHUNK_SIZE:     "10000"
  AMQ_HOST:       "amq-broker"
  AMQ_PORT:       "61616"
  SERVER_PORT:    "8081"
